export interface MenuItem {
  id: string
  name: string
  description: string
  emoji: string
  category: 'chicken' | 'beef' | 'fish'
  mealType: 'high-protein' | 'slim'
  leanPrice: number
  bulkPrice: number
  leanCalories: number
  bulkCalories: number
  leanProtein: number
  bulkProtein: number
  leanCarb: number
  bulkCarb: number
  leanFat: number
  bulkFat: number
  tags: string[]
  contains: string[]
  image: string
}

export const menuItems: MenuItem[] = [
  {
    id: 'aus-beef-mexican',
    name: 'Australian Beef with Mexican Sauce',
    description: 'Juicy Australian Beef infused with authentic Mexican-inspired sauce. Prepared with Spaghetti and tomato sauce, mildly spicy and rich in flavor.',
    emoji: '🥩🇲🇽🌶️',
    category: 'beef',
    mealType: 'high-protein',
    leanPrice: 295, bulkPrice: 350,
    leanCalories: 558, bulkCalories: 729,
    leanProtein: 56.5, bulkProtein: 75,
    leanCarb: 47.5, bulkCarb: 62,
    leanFat: 15.8, bulkFat: 20.1,
    tags: ['Sugar Free', 'Keto Friendly', 'Gluten Free', 'Soy Free', 'Egg Free', 'Nut Free'],
    contains: ['Tomato'],
    image: 'https://static.wixstatic.com/media/f269ec_e7ef20c39a2849b38fbe5e4a03e5c161~mv2.png'
  },
  {
    id: 'aus-beef-steak',
    name: 'Australian Beef Steak',
    description: 'Premium Australian Beef Steak served alongside aromatic garlic rice. Bold, juicy, and cooked to perfection.',
    emoji: '🥩🍚',
    category: 'beef',
    mealType: 'high-protein',
    leanPrice: 295, bulkPrice: 350,
    leanCalories: 558, bulkCalories: 729,
    leanProtein: 56.5, bulkProtein: 75,
    leanCarb: 47.5, bulkCarb: 62,
    leanFat: 15.8, bulkFat: 20.1,
    tags: ['Sugar Free', 'Keto Friendly', 'Gluten Free', 'Soy Free', 'Egg Free', 'Nut Free', 'Dairy Free'],
    contains: ['Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_927c761d49964ad1949148da52f522db~mv2.png'
  },
  {
    id: 'salmon-spaghetti',
    name: 'Grilled Salmon With Spaghetti',
    description: 'Tender grilled salmon over spaghetti with aromatic dry chili flakes — a bold, clean fusion of ocean freshness and Italian comfort.',
    emoji: '🐟🍝🌶️',
    category: 'fish',
    mealType: 'high-protein',
    leanPrice: 275, bulkPrice: 330,
    leanCalories: 516, bulkCalories: 671,
    leanProtein: 51.5, bulkProtein: 68,
    leanCarb: 45.5, bulkCarb: 58,
    leanFat: 14.2, bulkFat: 18.5,
    tags: ['Sugar Free', 'Keto Friendly', 'Gluten Free', 'Soy Free', 'Egg Free', 'Nut Free', 'Dairy Free'],
    contains: ['Fish', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_3cd9bc85b36542cebe07f5fa4fe55efa~mv2.png'
  },
  {
    id: 'chicken-paprika',
    name: 'Grilled Chicken with Paprika',
    description: 'Golden roasted potatoes paired with juicy grilled chicken seasoned with smoky paprika — a warm, rustic, and protein-rich plate that fuels your day the clean way.',
    emoji: '🍗🌶️🥔',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Gluten Free', 'Soy Free', 'Egg Free', 'Nut Free', 'Dairy Free'],
    contains: ['Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_d76e283a01ff46189d14169d601659dc~mv2.png'
  },
  {
    id: 'chicken-creamy-pasta',
    name: 'Grilled Chicken with Creamy Pasta',
    description: 'Tender roasted chicken paired with rich, creamy pasta — indulgently smooth yet clean and nourishing.',
    emoji: '🍗🍝',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Egg Free', 'Nut Free'],
    contains: ['Dairy', 'Lactose'],
    image: 'https://static.wixstatic.com/media/f269ec_29e7ed75b56a4b8296214e94475d73cb~mv2.png'
  },
  {
    id: 'seabass-steak',
    name: 'Seabass Steak',
    description: 'Premium seabass with golden crispy skin and moist tender center. Light, elegant, and deeply nourishing.',
    emoji: '🐟✨🌿',
    category: 'fish',
    mealType: 'high-protein',
    leanPrice: 275, bulkPrice: 330,
    leanCalories: 516, bulkCalories: 671,
    leanProtein: 51.5, bulkProtein: 68,
    leanCarb: 45.5, bulkCarb: 58,
    leanFat: 14.2, bulkFat: 18.5,
    tags: ['Sugar Free', 'Keto Friendly', 'Gluten Free', 'Soy Free', 'Egg Free', 'Nut Free'],
    contains: ['Fish'],
    image: 'https://static.wixstatic.com/media/f269ec_e7a3fead2d004467bff3f5ea4b064a20~mv2.png'
  },
  {
    id: 'chicken-pesto',
    name: 'Grilled Chicken with Pesto',
    description: 'Fresh meets flavorful! Juicy grilled chicken blanketed in vibrant, herby basil pesto — fragrant, garlicky, and absolutely irresistible.',
    emoji: '🌿🍗🇮🇹',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Keto Friendly', 'Gluten Free', 'Soy Free', 'Egg Free'],
    contains: ['Nuts (Pine Nuts)', 'Dairy'],
    image: 'https://static.wixstatic.com/media/f269ec_6d1b23676c144a7bb43cb4ed26a2bc6d~mv2.png'
  },
  {
    id: 'chicken-spaghetti',
    name: 'Grilled Chicken with Spaghetti',
    description: 'Tender, smoky grilled chicken on perfectly cooked spaghetti — high in protein, satisfying, and delicious enough to make healthy eating feel like a treat.',
    emoji: '🍗🍝🔥',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Soy Free', 'Egg Free', 'Nut Free'],
    contains: ['Gluten (Wheat)'],
    image: 'https://static.wixstatic.com/media/f269ec_cbba611d04454260995e4b26484191ae~mv2.png'
  },
  {
    id: 'spicy-chicken-garlic-rice',
    name: 'Spicy Chicken with Garlic Rice',
    description: 'Boldly spiced chicken with a fiery kick, served alongside aromatic golden garlic rice. Sizzling, savory, and satisfying — for those who like it hot and healthy!',
    emoji: '🌶️🍗🍚',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Gluten Free', 'Soy Free', 'Egg Free', 'Nut Free'],
    contains: ['Garlic', 'Chili'],
    image: 'https://static.wixstatic.com/media/f269ec_2ca25f6468b04947a30b76cd8518da20~mv2.png'
  },
  {
    id: 'chicken-satay-fried-rice',
    name: 'Grilled Chicken Satay with Fried Rice',
    description: 'Succulent grilled chicken skewers in rich nutty satay sauce — smoky, sweet, and savory. Paired with fragrant fried rice for a Southeast Asian-inspired clean meal.',
    emoji: '🍗🍚🥜',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 215,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Gluten Free', 'Egg Free'],
    contains: ['Peanuts', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_ab023e99cf9948e0aa3faee14503607a~mv2.png'
  },
  {
    id: 'chicken-bbq-truffle',
    name: 'Potato with Grilled Chicken BBQ Truffle',
    description: 'Crispy golden potatoes with BBQ-glazed grilled chicken elevated by luxurious truffle earthiness. Smoky, rich, and utterly unforgettable.',
    emoji: '🍖🍗🌿',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Gluten Free', 'Soy Free', 'Egg Free', 'Nut Free'],
    contains: ['Garlic', 'Truffle'],
    image: 'https://static.wixstatic.com/media/f269ec_d5ab9a3bea994646adf7cd458632b981~mv2.png'
  },
  {
    id: 'black-spaghetti-pesto',
    name: 'Black Spaghetti with Pesto Chicken',
    description: 'Jet-black squid-ink pasta with fragrant basil pesto and succulent golden-grilled chicken. Striking, bold, and absolutely delicious.',
    emoji: '🖤🍝🌿',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Soy Free', 'Egg Free'],
    contains: ['Gluten (Wheat)', 'Nuts (Pine Nuts)', 'Squid Ink'],
    image: 'https://static.wixstatic.com/media/f269ec_d78d42b268244404a05bef24f4c6ef73~mv2.png'
  },
  {
    id: 'chicken-korean-rice',
    name: 'Grilled Chicken with Korean Fried Rice',
    description: 'Juicy grilled chicken on wok-tossed Korean fried rice bursting with umami, sesame, and smoky Korean flavor. Bold, vibrant, and deeply satisfying.',
    emoji: '🇰🇷🍗🍚',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Gluten Free', 'Egg Free', 'Nut Free'],
    contains: ['Soy', 'Garlic', 'Sesame'],
    image: 'https://static.wixstatic.com/media/f269ec_4398de7cc6884430a248b42d2cd4433c~mv2.png'
  },
  {
    id: 'beef-yakiniku',
    name: 'Grilled Beef Yakiniku with Garlic Rice',
    description: 'Premium beef in sweet-savory Japanese yakiniku sauce, grilled to caramelized perfection on aromatic garlic rice. Rich, smoky umami in every bite.',
    emoji: '🥩🇯🇵🔥',
    category: 'beef',
    mealType: 'high-protein',
    leanPrice: 295, bulkPrice: 350,
    leanCalories: 558, bulkCalories: 729,
    leanProtein: 56.5, bulkProtein: 75,
    leanCarb: 47.5, bulkCarb: 62,
    leanFat: 15.8, bulkFat: 20.1,
    tags: ['Sugar Free', 'Gluten Free', 'Egg Free', 'Nut Free'],
    contains: ['Soy', 'Garlic', 'Sesame'],
    image: 'https://static.wixstatic.com/media/f269ec_f27e2992eb454a6696309c16f8302619~mv2.png'
  },
  {
    id: 'salmon-teriyaki-rice',
    name: 'Salmon Teriyaki with Salmon Fried Rice',
    description: 'Double the salmon, double the love! Teriyaki-glazed salmon fillet on savory salmon fried rice. The ultimate omega-3 clean seafood experience.',
    emoji: '🐟🍚✨',
    category: 'fish',
    mealType: 'high-protein',
    leanPrice: 275, bulkPrice: 330,
    leanCalories: 516, bulkCalories: 671,
    leanProtein: 51.5, bulkProtein: 68,
    leanCarb: 45.5, bulkCarb: 58,
    leanFat: 14.2, bulkFat: 18.5,
    tags: ['Sugar Free', 'Gluten Free', 'Egg Free', 'Nut Free'],
    contains: ['Fish', 'Soy', 'Sesame'],
    image: 'https://static.wixstatic.com/media/f269ec_8589351aaad94c36a9aab4836e971293~mv2.png'
  },
  {
    id: 'chicken-miso-pasta',
    name: 'Grilled Chicken with Pasta Miso Cream',
    description: 'Silky umami-rich miso cream sauce with al dente pasta and golden grilled chicken. Creamy, savory, and surprisingly light.',
    emoji: '🍗🍜🇯🇵',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Egg Free', 'Nut Free'],
    contains: ['Gluten (Wheat)', 'Soy (Miso)', 'Dairy'],
    image: 'https://static.wixstatic.com/media/f269ec_489ea548e8b247acbdb220751f6ac8c0~mv2.png'
  },
  {
    id: 'chicken-paprika-macaroni',
    name: 'Grilled Chicken Paprika with Macaroni',
    description: 'Smoky paprika-rubbed grilled chicken with tender hearty macaroni. Warm, rustic, and comfortingly nutritious.',
    emoji: '🍗🌶️🍝',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Soy Free', 'Egg Free', 'Nut Free'],
    contains: ['Gluten (Wheat)', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_3eb77bb0c1284c5781fd9873085a034d~mv2.png'
  },
  {
    id: 'potato-chicken-miso',
    name: 'Potato with Grilled Chicken Pasta Miso Cream',
    description: 'Fluffy roasted potatoes and grilled chicken with luscious miso cream pasta. Rich, silky, and packed with umami depth.',
    emoji: '🍖🍗🍜',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Egg Free', 'Nut Free'],
    contains: ['Gluten (Wheat)', 'Soy (Miso)', 'Dairy'],
    image: 'https://static.wixstatic.com/media/f269ec_ed9e9a5617ad420d81a0072ffafbe7cc~mv2.png'
  },
  {
    id: 'tobiko-pasta-chicken',
    name: 'Spaghetti Cream Tobiko with Grilled Chicken',
    description: 'Silky cream pasta with vibrant popping tobiko and juicy grilled chicken. Elegant, clean, and bursting with oceanic flavor.',
    emoji: '🍗🍝🟠',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Nut Free'],
    contains: ['Gluten (Wheat)', 'Fish Roe', 'Dairy', 'Egg'],
    image: 'https://static.wixstatic.com/media/f269ec_0e91137f402a4c729507a9f926b85a16~mv2.png'
  },
  {
    id: 'chicken-cashew',
    name: 'Stir Fried Chicken with Cashew Nut',
    description: 'Wok-tossed chicken with crunchy roasted cashews and crisp vegetables in a savory-sweet sauce. Light, nutty, and pure joy in a bowl.',
    emoji: '🍗🌿🥜',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Gluten Free', 'Egg Free'],
    contains: ['Cashew Nuts', 'Soy', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_a026de51b0fb44969c4596964d9e9789~mv2.png'
  },
  {
    id: 'salmon-soy-garlic-rice',
    name: 'Garlic Rice with Salmon Soy Sauce',
    description: 'Seared salmon in umami-packed soy sauce reduction on fragrant golden garlic rice. Clean, wholesome, and absolutely mouthwatering.',
    emoji: '🐟🍚🇯🇵',
    category: 'fish',
    mealType: 'high-protein',
    leanPrice: 275, bulkPrice: 330,
    leanCalories: 516, bulkCalories: 671,
    leanProtein: 51.5, bulkProtein: 68,
    leanCarb: 45.5, bulkCarb: 58,
    leanFat: 14.2, bulkFat: 18.5,
    tags: ['Sugar Free', 'Gluten Free', 'Egg Free', 'Nut Free'],
    contains: ['Fish', 'Soy', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_9046a9b0424e4bd4af1ef3121d29275c~mv2.png'
  },
  {
    id: 'sweet-potato-chicken-burger',
    name: 'Sweet Potato with Chicken Burger',
    description: 'Juicy grilled chicken patty with naturally sweet fiber-rich roasted sweet potato. Guilt-free, satisfying, and hits every flavor note.',
    emoji: '🍠🍔🍗',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Soy Free', 'Nut Free'],
    contains: ['Gluten (Wheat)', 'Egg', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_f9a73ed8a935450084fe4b108cabe76b~mv2.png'
  },
  {
    id: 'chicken-afritada-pasta',
    name: 'Chicken Afritada Pasta',
    description: 'A Filipino-inspired clean food gem! Slow-simmered chicken in a rich tomato-based sauce with tender vegetables, tossed with hearty pasta. Warm, comforting, and loaded with protein.',
    emoji: '🍗🍝🇵🇭',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 520, bulkCalories: 680,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Soy Free', 'Egg Free', 'Nut Free'],
    contains: ['Gluten (Wheat)', 'Tomato', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_e520cd67c52b4a3f8c306c639eb4accb~mv2.png'
  },
  {
    id: 'salmon-bbq-garlic-rice',
    name: 'Garlic Rice with Salmon BBQ',
    description: 'Gorgeous salmon fillet glazed in smoky BBQ sauce — perfectly charred outside, moist and flaky inside. Paired with aromatic golden garlic rice. Clean BBQ bliss.',
    emoji: '🐟🍚🔥',
    category: 'fish',
    mealType: 'high-protein',
    leanPrice: 275, bulkPrice: 330,
    leanCalories: 520, bulkCalories: 680,
    leanProtein: 51.5, bulkProtein: 68,
    leanCarb: 45.5, bulkCarb: 58,
    leanFat: 14.2, bulkFat: 18.5,
    tags: ['Sugar Free', 'Gluten Free', 'Egg Free', 'Nut Free'],
    contains: ['Fish', 'Garlic', 'Tomato'],
    image: 'https://static.wixstatic.com/media/f269ec_4a6a276238db4eb58f37b7446c8acb43~mv2.png'
  },
  {
    id: 'beef-teriyaki',
    name: 'Beef Teriyaki',
    description: 'A timeless Japanese classic done the clean way! Tender premium beef slices glazed in a glossy, sweet-savory teriyaki sauce — caramelized to perfection with deep umami flavor in every bite.',
    emoji: '🥩🇯🇵✨',
    category: 'beef',
    mealType: 'high-protein',
    leanPrice: 295, bulkPrice: 350,
    leanCalories: 560, bulkCalories: 720,
    leanProtein: 56.5, bulkProtein: 75,
    leanCarb: 47.5, bulkCarb: 62,
    leanFat: 15.8, bulkFat: 20.1,
    tags: ['Sugar Free', 'Gluten Free', 'Egg Free', 'Nut Free', 'Dairy Free'],
    contains: ['Soy', 'Sesame', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_5602a99cb01d4d8eae81adfb1bbfa06d~mv2.png'
  },
  {
    id: 'pesto-spicy-chicken-steak',
    name: 'Pasta Pesto with Spicy Chicken Steak',
    description: 'Vibrant herby basil pesto pasta paired with a boldly spiced, seared chicken steak that packs a serious punch. Fiery, fresh, and fantastically nutritious.',
    emoji: '🌶️🍝🌿',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 520, bulkCalories: 680,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Soy Free', 'Egg Free'],
    contains: ['Gluten (Wheat)', 'Nuts (Pine Nuts)', 'Dairy', 'Garlic'],
    image: 'https://static.wixstatic.com/media/f269ec_5b564e55be354373a26c6135e52c4a22~mv2.png'
  },
  {
    id: 'chicken-new-orleans',
    name: 'Grilled Chicken New Orleans',
    description: 'Bold Cajun-style spiced grilled chicken — smoky, spicy, herby, and outrageously flavorful with Southern American soul.',
    emoji: '🍗🇺🇸🔥',
    category: 'chicken',
    mealType: 'high-protein',
    leanPrice: 215, bulkPrice: 250,
    leanCalories: 519, bulkCalories: 664,
    leanProtein: 62.6, bulkProtein: 75,
    leanCarb: 40.5, bulkCarb: 55,
    leanFat: 11.8, bulkFat: 16,
    tags: ['Sugar Free', 'Gluten Free', 'Soy Free', 'Egg Free', 'Nut Free', 'Dairy Free'],
    contains: ['Garlic', 'Chili', 'Paprika'],
    image: 'https://static.wixstatic.com/media/f269ec_f0e27be21aef4ad5b04ad0124802fbc4~mv2.png'
  }
]
